### ISSUE TITLE
Broken pipe errors

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/moments#17]
```
[2023-09-27T13:54:55Z INFO  moments] Populating cache...
[2023-09-27T13:54:55Z INFO  moments] Serving at 0.0.0.0:3000
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', src/websocket.rs:27:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }called `Result::unwrap()` on an `Err` value: Error { inner: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }', ', src/websocket.rssrc/websocket.rs::2727::3636

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }', src/websocket.rs:27:36
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }', src/websocket.rs:27:36
```

**Comment by schmidma** [comment]
These errors occur, when the kiosk closes the socket, all errors are now suppressed (silent) and the socket is closed on error
